{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "aaab4c54",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "import json\n",
    "from pathlib import Path\n",
    "from delfos.market.session import Session\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9a03548a",
   "metadata": {},
   "outputs": [],
   "source": [
    "session = Session(period=6)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bac158d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(Path(\"./delfos/data/market/tickers.json\"), encoding=\"utf8\") as tickers_file:\n",
    "    TICKERS_DICT = json.load(tickers_file) #dicionário com todas as informações fixas das ações listadas na B3\n",
    "    \n",
    "FUNDAMENTUS_URL = \"https://fundamentus.com.br/detalhes.php?papel=\"\n",
    "REQUESTS_HEADER = {\"User-Agent\": \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36\", 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "268b511f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#PRINCIPAIS AÇÕES DA BOLSA (269 ATÉ O MOMENTO)\n",
    "tickers_list_url = \"https://www.mobills.com.br/blog/investimentos/cnpj-das-empresas-listadas-na-b3/\" #trocar?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a251f0ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "possible_new_tickers_df = pd.read_html(requests.get(tickers_list_url).text)[0]\n",
    "possible_new_tickers_df = possible_new_tickers_df.drop_duplicates(keep=\"last\")\n",
    "possible_new_tickers_df[\"TICKER\"] = possible_new_tickers_df[\"TICKER\"].str.strip()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4905ecf4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "110"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-403:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread 'SSLDispatcher' object has no attribute 'timeout'\n",
      "Thread-58:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-344:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    Exception in thread Thread-360:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "        self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "Exception in thread Thread-348:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "Exception in thread     self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "Thread-373:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-218:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-363:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "Exception in thread Thread-62:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "Exception in thread Thread-342:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "Exception in thread Thread-396:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    Exception in thread Thread-253:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "        self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Exception in thread     self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "Thread-247:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "        self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "        self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Exception in thread Thread-63:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "        raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "        raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-428:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-92:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-395:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-460:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-389:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "Exception in thread Thread-477:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Exception in thread Thread-40:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-280:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Thread-203'SSLDispatcher' object has no attribute 'timeout'\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "        self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "Exception in thread Thread-482:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-281:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "Exception in thread Thread-435:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "Exception in thread Thread-473:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "        raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    Connection to remote host was lost.\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "Connection to remote host was lost.\n",
      "        raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "Connection to remote host was lost.\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-67:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    'SSLDispatcher' object has no attribute 'timeout'\n",
      "self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread Thread-99:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Connection to remote host was lost.\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "Exception in thread Thread-127:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread Thread-163:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread Thread-28:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "        self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    'SSLDispatcher' object has no attribute 'timeout'\n",
      "self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Exception in thread Thread-139:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-32:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-499:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-503:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-498:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-346:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-521:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-531:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "Exception in thread Thread-74:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-279:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-97:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-420:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-450:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-57:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "Exception in thread Thread-235:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-471:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-461:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-275:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-263:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "Exception in thread Thread-468:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "Exception in thread Thread-219:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-526:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-527:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n",
      "Connection to remote host was lost.\n",
      "'SSLDispatcher' object has no attribute 'timeout'\n",
      "Exception in thread Thread-508:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 125, in _run\n",
      "    self.stop()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\yflive\\streamer.py\", line 113, in stop\n",
      "    self._ws_thread.join()\n",
      "  File \"C:\\Users\\bgalv\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py\", line 1050, in join\n",
      "    raise RuntimeError(\"cannot join current thread\")\n",
      "RuntimeError: cannot join current thread\n"
     ]
    }
   ],
   "source": [
    "#TICKERS QUE ESTÃO NO URL MAS NÃO ESTÃO NO SISTEMA\n",
    "new_tickers = []\n",
    "for possible_ticker in possible_new_tickers_df[\"TICKER\"]:\n",
    "    if possible_ticker not in session.stocks:\n",
    "        new_tickers.append(possible_ticker)\n",
    "        \n",
    "len(new_tickers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "561e1e2a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#PEGAR DADOS QUE FALTAM DAS NOVAS AÇÕES E GRAVAR NO ARQUIVO JSON\n",
    "\n",
    "stocks_not_found = 0\n",
    "for ticker in new_tickers:\n",
    "    try:\n",
    "        requested_data = requests.get(FUNDAMENTUS_URL + ticker, headers=REQUESTS_HEADER ) #chamada GET ao site da Fundamentus\n",
    "        html_tables_list = pd.read_html(requested_data.text)\n",
    "\n",
    "        session_name = html_tables_list[0][1][2] #nome da companhia\n",
    "\n",
    "        cnpj = possible_new_tickers_df[\"CNPJ\"][possible_new_tickers_df[\"TICKER\"] == ticker].iloc[0]\n",
    "        name = possible_new_tickers_df[\"RAZÃO SOCIAL\"][possible_new_tickers_df[\"TICKER\"] == ticker].iloc[0]\n",
    "\n",
    "        sector = html_tables_list[0][1][3] #setor da companhia\n",
    "        sub_sector = html_tables_list[0][1][4] #sub setor da companhia\n",
    "        segment = html_tables_list[0][1][4] #segmento da companhia\n",
    "\n",
    "        ticker_dict = {ticker: {'Nome de pregão':session_name, \"CNPJ\": cnpj, \"Nome\": name, \"Setor\": sector, \"Sub Setor\":sub_sector, \"Segmento\": segment}}\n",
    "\n",
    "        TICKERS_DICT.update(ticker_dict)\n",
    "        \n",
    "        with open(Path(\"./delfos/data/market/tickers.json\"), \"w\", encoding=\"utf8\") as json_file:\n",
    "            json.dump(TICKERS_DICT, json_file, indent=4, separators=(',',': '))\n",
    "    \n",
    "    except Exception as e:\n",
    "        stocks_not_found +=1\n",
    "        pass #O PAPEL NÃO ESTÁ NO SITE FUNDAMENTUS, PORTANTO NÃO APRESENTA TODAS AS INFOS NECESSÁRIAS PARA SER ADICIONADO AO JSON\n",
    "\n",
    "print(stocks_not_found)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "db0054df",
   "metadata": {},
   "outputs": [],
   "source": [
    "#TICKERS QUE ESTÃO NO SISTEMA MAS NÃO ESTÃO NO URL\n",
    "possible_old_tickers = []\n",
    "for ticker in session.stocks:\n",
    "    if ticker not in possible_new_tickers_df[\"TICKER\"].tolist():\n",
    "        possible_old_tickers.append(ticker)\n",
    "        \n",
    "len(possible_old_tickers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e3ea663",
   "metadata": {},
   "outputs": [],
   "source": [
    "possible_old_tickers"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
